### ISSUE TITLE
Personalizeed message 

### ISSUE THREAD

**Issue by meghanabhange** [meghanabhange/autographx#5]
- Writing a message that will be common to every student. 

```
Hey {student name}, 
the message
```

- Something that we will remember and keep with us for a long time :)

**Comment by radhikasethi2011** [comment]
and a link to 'you can count on me' - Bruno mars, to play it along whilst they read it 😝

**Comment by meghanabhange** [comment]
We are skipping this for now. Will reopen when we have more bandwidth
