### ISSUE TITLE
Some people’s entries are missing completely. Like no pdf is generated

### ISSUE THREAD

**Issue by meghanabhange** [meghanabhange/autographx#58]
We can try to figure out why this is happening? Like come up with FAQ --"did you check your name in csv" 

It can also be a problem from our end 🤷🏻‍♀️

**Comment by meghanabhange** [comment]
Some of the missing pdfs are for 

- Shriya Mendhule
- Aayushi Bansal
- Bhavana B 
- Simran Kulkarni

**Comment by radhikasethi2011** [comment]
all of the mentioned had their name in df.index as 'name <space> surname' which caused an error, as 
* df["query_name"] had a space, whereas the filename from gdrive had no spaces. 
* What didn't match is : 
![image](https://user-images.githubusercontent.com/44310177/87845946-b7836c00-c8e9-11ea-91be-34147aa8e86e.png)

**Comment by radhikasethi2011** [comment]
not a problem from our end! 
It was entered in the csv with a space

**Comment by meghanabhange** [comment]
One of the reasons was trailing spaces. They were either in 

- Folder Name
- First Name or Last Name

**Comment by meghanabhange** [comment]
One more error that was noticed us capitalisations in folder names under yearbookENTC
